//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalenderJawa.LocalizedResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KalenderJawa.LocalizedResources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2012 Ahmad Masykur.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day view calendar.
        /// </summary>
        public static string DailyViewCalendarLabel {
            get {
                return ResourceManager.GetString("DailyViewCalendarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string DayLabel {
            get {
                return ResourceManager.GetString("DayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fri.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gregorian, java day name.
        /// </summary>
        public static string GregorianAndJavaDayNameLabel {
            get {
                return ResourceManager.GetString("GregorianAndJavaDayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D: Gregorian day of month.
        /// </summary>
        public static string GregorianDayOfMonthLabel {
            get {
                return ResourceManager.GetString("GregorianDayOfMonthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is Javansese calendar system that commonly used in Central Java and East Java, Indonesia. It&apos;s unique because calculation and naming are mixed from Islamic and Budish and also Western (Gregorian) calendar system..
        /// </summary>
        public static string HelpParagraph1 {
            get {
                return ResourceManager.GetString("HelpParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalender Jawa application is displays Java calendar system based on Sultan Agung algoritm applied since 1625 AD. In addition, it displays hijri calender as well..
        /// </summary>
        public static string HelpParagraph2 {
            get {
                return ResourceManager.GetString("HelpParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are two display mode: monthly and daily. Main display is gregorian calendar, java and hijri calendar displays as secondary information. Here is calendar layout description:.
        /// </summary>
        public static string HelpParagraph3 {
            get {
                return ResourceManager.GetString("HelpParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hijri day month year.
        /// </summary>
        public static string HijriDayMonthYearLabel {
            get {
                return ResourceManager.GetString("HijriDayMonthYearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C: Hijri day of month.
        /// </summary>
        public static string HijriDayOfMonthLabel {
            get {
                return ResourceManager.GetString("HijriDayOfMonthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java day month year.
        /// </summary>
        public static string JavaDayMonthYearLabel {
            get {
                return ResourceManager.GetString("JavaDayMonthYearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A: Java day name.
        /// </summary>
        public static string JavaDayNameLabel {
            get {
                return ResourceManager.GetString("JavaDayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B: Java day of month.
        /// </summary>
        public static string JavaDayOfMonthLabel {
            get {
                return ResourceManager.GetString("JavaDayOfMonthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java season name.
        /// </summary>
        public static string JavaSeasonNameLabel {
            get {
                return ResourceManager.GetString("JavaSeasonNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mon.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string MonthLabel {
            get {
                return ResourceManager.GetString("MonthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month view calendar.
        /// </summary>
        public static string MonthlyViewCalendarLabel {
            get {
                return ResourceManager.GetString("MonthlyViewCalendarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information please see.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or email to.
        /// </summary>
        public static string OrEmailTo {
            get {
                return ResourceManager.GetString("OrEmailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin.
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sat.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to season.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season name.
        /// </summary>
        public static string SeasonNameLabel {
            get {
                return ResourceManager.GetString("SeasonNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season schedule.
        /// </summary>
        public static string SeasonScheduleLabel {
            get {
                return ResourceManager.GetString("SeasonScheduleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seasons.
        /// </summary>
        public static string SeasonsLabel {
            get {
                return ResourceManager.GetString("SeasonsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season view calendar.
        /// </summary>
        public static string SeasonViewCalendarLabel {
            get {
                return ResourceManager.GetString("SeasonViewCalendarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sun.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thu.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tue.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wed.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
    }
}
